2024-05-30 09:00:31.725 [info] (Client) Pylance async client (2024.5.1) started with python extension (2024.6.0)
2024-05-30 09:00:33.575 [info] [Info  - 9:00:33 AM] (351) Pylance language server 2024.5.1 (pyright version 1.1.360, commit 4bc8428d) starting
2024-05-30 09:00:33.576 [info] [Info  - 9:00:33 AM] (351) Server root directory: file:///home/ndao/.vscode-server/extensions/ms-python.vscode-pylance-2024.5.1/dist
2024-05-30 09:00:33.593 [info] [Info  - 9:00:33 AM] (351) Starting service instance "ndao"
2024-05-30 09:00:33.609 [info] [Info  - 9:00:33 AM] (351) Auto-Indent enabled
2024-05-30 09:00:33.752 [info] [Info  - 9:00:33 AM] (351) Setting pythonPath for service "ndao": "/bin/python3"
2024-05-30 09:00:33.752 [info] [Info  - 9:00:33 AM] (351) Setting environmentName for service "ndao": "3.8.10 (global)"
2024-05-30 09:00:33.832 [info] [Info  - 9:00:33 AM] (351) Assuming Python version 3.8.10.final.0
2024-05-30 09:00:34.640 [info] [Info  - 9:00:34 AM] (351) No source files found.
2024-05-30 09:00:35.274 [info] [Info  - 9:00:35 AM] (351) Background analysis(1) root directory: file:///home/ndao/.vscode-server/extensions/ms-python.vscode-pylance-2024.5.1/dist
2024-05-30 09:00:35.285 [info] [Info  - 9:00:35 AM] (351) Background analysis(1) started
